  ;; Added to the PGlite core module built from pinned sources by prepare-engine.py.
  ;; Canonical ABI allocations share the engine's allocator and linear memory.
  (export "_initialize" (func $__wasm_call_ctors))
  (func (export "cabi_realloc") (param $old i32) (param i32) (param i32) (param $size i32) (result i32)
    (local $p i32)
    (local.set $p (call $realloc (local.get $old) (local.get $size)))
    (if (i32.and (i32.eqz (local.get $p)) (i32.ne (local.get $size) (i32.const 0))) (then unreachable))
    (local.get $p))
  (func $bridge_cstr (param $p i32) (param $len i32) (result i32)
    (local $out i32)
    (local.set $out (call $malloc (i32.add (local.get $len) (i32.const 1))))
    (if (i32.eqz (local.get $out)) (then unreachable))
    (memory.copy (local.get $out) (local.get $p) (local.get $len))
    (i32.store8 (i32.add (local.get $out) (local.get $len)) (i32.const 0))
    (local.get $out))
  (func (export "di-framework:pglite-engine/engine@0.1.0#set-env")
    (param $kp i32) (param $kl i32) (param $vp i32) (param $vl i32) (result i32)
    (local $k i32) (local $v i32) (local $rc i32)
    (local.set $k (call $bridge_cstr (local.get $kp) (local.get $kl)))
    (local.set $v (call $bridge_cstr (local.get $vp) (local.get $vl)))
    (local.set $rc (call $setenv (local.get $k) (local.get $v) (i32.const 1)))
    (call $free (local.get $kp)) (call $free (local.get $vp))
    (call $free (local.get $k)) (call $free (local.get $v))
    (local.get $rc))
  (func (export "di-framework:pglite-engine/engine@0.1.0#start")
    (param $args i32) (param $len i32) (result i32)
    (local $argv i32) (local $i i32) (local $item i32)
    ;; main retains argv, so keep this one allocation for the engine lifetime.
    (local.set $argv (call $malloc (i32.mul (i32.add (local.get $len) (i32.const 1)) (i32.const 4))))
    (if (i32.eqz (local.get $argv)) (then unreachable))
    (block $done (loop $next
      (br_if $done (i32.ge_u (local.get $i) (local.get $len)))
      (local.set $item (i32.add (local.get $args) (i32.mul (local.get $i) (i32.const 8))))
      (i32.store (i32.add (local.get $argv) (i32.mul (local.get $i) (i32.const 4)))
        (call $bridge_cstr (i32.load (local.get $item)) (i32.load offset=4 (local.get $item))))
      (call $free (i32.load (local.get $item)))
      (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $next)))
    (i32.store (i32.add (local.get $argv) (i32.mul (local.get $len) (i32.const 4))) (i32.const 0))
    (call $free (local.get $args))
    (call $main (local.get $len) (local.get $argv)))
  (export "di-framework:pglite-engine/engine@0.1.0#initdb" (func $pgl_initdb))
  (global $bridge_addr (mut i32) (i32.const 0))
  (global $bridge_size (mut i32) (i32.const 0))
  (func (export "di-framework:pglite-engine/engine@0.1.0#backend")
    (local $channel i32)
    (call $pgl_backend)
    (local.set $channel (call $get_channel))
    (if (i32.lt_s (local.get $channel) (i32.const 0)) (then unreachable))
    (global.set $bridge_addr (call $get_buffer_addr (local.get $channel)))
    (global.set $bridge_size (call $get_buffer_size (local.get $channel))))
  (export "di-framework:pglite-engine/engine@0.1.0#step" (func $interactive_one))
  (global $bridge_result (mut i32) (i32.const 0))
  (func (export "di-framework:pglite-engine/engine@0.1.0#write")
    (param $p i32) (param $len i32) (result i32)
    (if (i32.ge_u (local.get $len) (global.get $bridge_size))
      (then (call $free (local.get $p)) (return (i32.const 0))))
    (call $use_wire (i32.const 1))
    (memory.copy (global.get $bridge_addr) (local.get $p) (local.get $len))
    (call $free (local.get $p))
    (call $interactive_write (local.get $len))
    (i32.const 1))
  (func (export "di-framework:pglite-engine/engine@0.1.0#read") (result i32)
    (local $n i32) (local $p i32)
    (if (i32.eqz (global.get $bridge_result))
      (then (global.set $bridge_result (call $malloc (i32.const 8)))))
    (if (i32.eqz (global.get $bridge_result)) (then unreachable))
    (local.set $n (call $interactive_read))
    (if (i32.lt_s (local.get $n) (i32.const 0)) (then unreachable))
    (local.set $p (call $di_reply_ptr))
    (i32.store (global.get $bridge_result) (local.get $p))
    (i32.store offset=4 (global.get $bridge_result) (local.get $n))
    (global.get $bridge_result))
  (func (export "cabi_post_di-framework:pglite-engine/engine@0.1.0#read") (param $ret i32)
    ;; Lift copied the reply before acknowledging it to the engine.
    (if (i32.load offset=4 (local.get $ret)) (then
      (call $di_reply_reset)
      (call $interactive_write (i32.const 0)))))
