//! di-framework: validation of repository names, digests, tags and upload
//! session ids against the OCI distribution-spec grammar *before* any of them
//! becomes part of a blobstore object key (see [`crate::keys`]). Upstream built
//! keys from the raw path segments, so `..` or other separators could reach the
//! storage backend.

use crate::Response;
use crate::http::error_response;
use crate::route::Route;
use crate::util::query_param;

/// `[a-z0-9]+((\.|_|__|-+)[a-z0-9]+)*(\/[a-z0-9]+((\.|_|__|-+)[a-z0-9]+)*)*`
pub(crate) fn is_valid_name(name: &str) -> bool {
    !name.is_empty() && name.len() <= 255 && name.split('/').all(is_valid_name_component)
}

fn is_valid_name_component(component: &str) -> bool {
    let alnum = |c: u8| c.is_ascii_lowercase() || c.is_ascii_digit();
    let bytes = component.as_bytes();
    let (Some(&first), Some(&last)) = (bytes.first(), bytes.last()) else {
        return false;
    };
    if !alnum(first) || !alnum(last) {
        return false;
    }
    // Separators between alphanumeric runs: `.`, `_`, `__` or one or more `-`.
    let mut run = String::new();
    for &c in bytes {
        if alnum(c) {
            if !run.is_empty() {
                let ok = matches!(run.as_str(), "." | "_" | "__") || run.bytes().all(|b| b == b'-');
                if !ok {
                    return false;
                }
                run.clear();
            }
        } else if matches!(c, b'.' | b'_' | b'-') {
            run.push(c as char);
        } else {
            return false;
        }
    }
    true
}

/// `[a-zA-Z0-9_][a-zA-Z0-9._-]{0,127}`
pub(crate) fn is_valid_tag(tag: &str) -> bool {
    let bytes = tag.as_bytes();
    let Some(&first) = bytes.first() else {
        return false;
    };
    bytes.len() <= 128
        && (first.is_ascii_alphanumeric() || first == b'_')
        && bytes
            .iter()
            .all(|&c| c.is_ascii_alphanumeric() || matches!(c, b'.' | b'_' | b'-'))
}

/// `algorithm ":" encoded` with algorithm `[a-z0-9]+([+._-][a-z0-9]+)*` and
/// encoded `[a-zA-Z0-9=_-]+`; `sha256` and `sha512` must be lowercase hex of the
/// right length.
pub(crate) fn is_valid_digest(digest: &str) -> bool {
    let Some((algorithm, encoded)) = digest.split_once(':') else {
        return false;
    };
    let alnum = |c: u8| c.is_ascii_lowercase() || c.is_ascii_digit();
    let algorithm_ok = !algorithm.is_empty()
        && algorithm
            .split(['+', '.', '_', '-'])
            .all(|part| !part.is_empty() && part.bytes().all(alnum));
    let encoded_ok = !encoded.is_empty()
        && encoded
            .bytes()
            .all(|c| c.is_ascii_alphanumeric() || matches!(c, b'=' | b'_' | b'-'));
    if !algorithm_ok || !encoded_ok {
        return false;
    }
    let hex = |len: usize| {
        encoded.len() == len
            && encoded
                .bytes()
                .all(|c| c.is_ascii_digit() || (b'a'..=b'f').contains(&c))
    };
    match algorithm {
        "sha256" => hex(64),
        "sha512" => hex(128),
        _ => true,
    }
}

/// Upload session ids are generated by [`crate::util::new_session_id`] (hex).
pub(crate) fn is_valid_session(session: &str) -> bool {
    !session.is_empty()
        && session.len() <= 128
        && session
            .bytes()
            .all(|c| c.is_ascii_alphanumeric() || matches!(c, b'_' | b'-'))
}

/// The distribution-spec error a route or query would raise, if any.
pub(crate) fn check(route: &Route<'_>, query: &str) -> Option<(&'static str, &'static str)> {
    const NAME: (&str, &str) = ("NAME_INVALID", "invalid repository name");
    const DIGEST: (&str, &str) = ("DIGEST_INVALID", "invalid digest");
    const TAG: (&str, &str) = ("TAG_INVALID", "invalid tag");
    const SESSION: (&str, &str) = ("BLOB_UPLOAD_INVALID", "invalid upload session");
    let name = match *route {
        Route::TagsList { name } | Route::UploadInit { name } => name,
        Route::Referrers { name, digest } | Route::Blob { name, digest } => {
            if !is_valid_digest(digest) {
                return Some(DIGEST);
            }
            name
        }
        Route::Manifest { name, reference } => {
            if reference.contains(':') {
                if !is_valid_digest(reference) {
                    return Some(DIGEST);
                }
            } else if !is_valid_tag(reference) {
                return Some(TAG);
            }
            name
        }
        Route::Upload { name, session } => {
            if !is_valid_session(session) {
                return Some(SESSION);
            }
            name
        }
    };
    if !is_valid_name(name) {
        return Some(NAME);
    }
    for key in ["digest", "mount"] {
        if query_param(query, key).is_some_and(|d| !is_valid_digest(&d)) {
            return Some(DIGEST);
        }
    }
    if query_param(query, "from").is_some_and(|n| !is_valid_name(&n)) {
        return Some(NAME);
    }
    None
}

/// `400` with the spec error code when [`check`] rejects the request.
pub(crate) fn reject(route: &Route<'_>, query: &str) -> Option<Response> {
    check(route, query).map(|(code, message)| error_response(400, code, message))
}

#[cfg(test)]
mod tests {
    use super::*;

    const SHA: &str = "sha256:0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef";

    #[test]
    fn names_follow_the_distribution_spec() {
        for ok in ["a", "library/nginx", "a.b_c__d---e/f0", "x/y/z"] {
            assert!(is_valid_name(ok), "{ok}");
        }
        for bad in [
            "", "..", "a/..", "../a", "a//b", "/a", "a/", "A", "a..b", "a___b", "a_.b", "-a", "a-",
            "a b", "a%2f", "a\\b",
        ] {
            assert!(!is_valid_name(bad), "{bad}");
        }
        assert!(!is_valid_name(&"a".repeat(256)));
    }

    #[test]
    fn tags_follow_the_distribution_spec() {
        for ok in ["latest", "v1.2.3", "_x", "A-b.c_d"] {
            assert!(is_valid_tag(ok), "{ok}");
        }
        for bad in ["", ".hidden", "-x", "..", "a/b", "a:b"] {
            assert!(!is_valid_tag(bad), "{bad}");
        }
        assert!(is_valid_tag(&"a".repeat(128)));
        assert!(!is_valid_tag(&"a".repeat(129)));
    }

    #[test]
    fn digests_are_algorithm_colon_encoded() {
        assert!(is_valid_digest(SHA));
        assert!(is_valid_digest(
            "multihash+base58:QmRZxt2b1FVZPNqd8hsiykDL3TdBDeTSPX9Kv46HmX4Gx8"
        ));
        for bad in [
            "",
            "sha256",
            "sha256:",
            ":abc",
            "sha256:../../etc",
            "sha256:ABCDEF0123456789abcdef0123456789abcdef0123456789abcdef0123456789",
            "sha256:abc",
            "SHA256:abc",
            "sha256:abc/def",
            "a..b:abc",
        ] {
            assert!(!is_valid_digest(bad), "{bad}");
        }
    }

    #[test]
    fn routes_and_queries_are_checked_with_spec_error_codes() {
        let code = |route: Route<'_>, query: &str| check(&route, query).map(|(c, _)| c);
        assert_eq!(code(Route::TagsList { name: "a/b" }, ""), None);
        assert_eq!(
            code(Route::TagsList { name: "a/../b" }, ""),
            Some("NAME_INVALID")
        );
        assert_eq!(
            code(
                Route::Blob {
                    name: "a",
                    digest: SHA
                },
                ""
            ),
            None
        );
        assert_eq!(
            code(
                Route::Blob {
                    name: "a",
                    digest: "sha256:.."
                },
                ""
            ),
            Some("DIGEST_INVALID")
        );
        assert_eq!(
            code(
                Route::Referrers {
                    name: "..",
                    digest: SHA
                },
                ""
            ),
            Some("NAME_INVALID")
        );
        assert_eq!(
            code(
                Route::Manifest {
                    name: "a",
                    reference: "v1"
                },
                ""
            ),
            None
        );
        assert_eq!(
            code(
                Route::Manifest {
                    name: "a",
                    reference: SHA
                },
                ""
            ),
            None
        );
        assert_eq!(
            code(
                Route::Manifest {
                    name: "a",
                    reference: ".."
                },
                ""
            ),
            Some("TAG_INVALID")
        );
        assert_eq!(
            code(
                Route::Manifest {
                    name: "a",
                    reference: "x:.."
                },
                ""
            ),
            Some("DIGEST_INVALID")
        );
        assert_eq!(
            code(
                Route::Upload {
                    name: "a",
                    session: ".."
                },
                ""
            ),
            Some("BLOB_UPLOAD_INVALID")
        );
        assert_eq!(
            code(
                Route::Upload {
                    name: "a",
                    session: "0af3"
                },
                ""
            ),
            None
        );
        assert_eq!(
            code(Route::UploadInit { name: "a" }, "digest=sha256%3A.."),
            Some("DIGEST_INVALID")
        );
        assert_eq!(
            code(
                Route::UploadInit { name: "a" },
                &format!("mount={SHA}&from=..%2Fx")
            ),
            Some("NAME_INVALID")
        );
        assert_eq!(
            code(
                Route::UploadInit { name: "a" },
                &format!("mount={SHA}&from=b")
            ),
            None
        );
    }
}
