/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/auth/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Describe how to log in
         * @description The account this controller serves and the identity server to obtain a credential from. The only unauthenticated operation.
         */
        get: operations["authInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke the credential
         * @description Revokes the bearer token at the identity server (or the API key) so it stops working everywhere.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/whoami": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Resolve the caller
         * @description The user, role, and credential the bearer token stands for in this account.
         */
        get: operations["whoami"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/deploy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apply a deployment
         * @description Validates the bundle and starts the rollout. Progress is streamed by the logs operation of the service.
         */
        post: operations["deploy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/deploy/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview a deployment
         * @description Validates the bundle and reports what applying it would change in the given environment, without changing anything.
         */
        post: operations["previewDeploy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/deploy/registry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the tenant registry
         * @description The tenant's own OCI registry: its URL and how to log in. Pull is open to viewers and developers; push needs developer. No credential is minted.
         */
        get: operations["registry"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/deployments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List deployments
         * @description Deployments of the environment, newest first, optionally for one service.
         */
        get: operations["deployments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/deployments/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Summarize deployments */
        get: operations["deploymentStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/deployments/rollback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Roll a service back
         * @description Starts a rollout of an earlier deployment, the previous one unless `to` names it.
         */
        post: operations["rollback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/secrets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List secrets
         * @description Names and update times only; secret values are never returned.
         */
        get: operations["secrets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/secrets/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set a secret
         * @description Creates or replaces the secret. The CLI reads the value from a file or stdin so it stays out of shell history.
         */
        put: operations["setSecret"];
        post?: never;
        /** Unset a secret */
        delete: operations["unsetSecret"];
        options?: never;
        head?: never;
        /**
         * Update a secret
         * @description Replaces the value of an existing secret; 404 when it does not exist.
         */
        patch: operations["updateSecret"];
        trace?: never;
    };
    "/v1/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a service
         * @description Creates an http, cron, or worker service in the environment. Type-specific fields follow the type.
         */
        post: operations["createService"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/services/{service}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read or follow service logs
         * @description Server-sent events (`text/event-stream`). Each `log` event carries one LogEvent as JSON; an `end` event closes the stream. With `follow` the stream stays open until the client disconnects.
         */
        get: operations["logs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/services/{service}/proxy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Open a tunnel to a service
         * @description Issues a short-lived tunnel session to one port of the service. The session URL takes the same bearer.
         */
        post: operations["proxy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/vars/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set a var
         * @description Creates or replaces the var. The CLI reads the value from a file or stdin so it stays out of shell history.
         */
        put: operations["setVar"];
        post?: never;
        /** Unset a var */
        delete: operations["unsetVar"];
        options?: never;
        head?: never;
        /**
         * Update a var
         * @description Replaces the value of an existing var; 404 when it does not exist.
         */
        patch: operations["updateVar"];
        trace?: never;
    };
    "/v1/vars": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List vars
         * @description Names, values, and update times of the environment variables.
         */
        get: operations["vars"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Empty: Record<string, never>;
        /** @description RFC 9457 problem details; every error response uses it. */
        Problem: {
            type?: string;
            title: string;
            /** Format: int32 */
            status: number;
            detail?: string;
        };
        /** @description What a CLI needs before it holds a credential: the account this controller serves and the identity server to log in with. */
        AuthInfo: {
            account: string;
            /** Format: uri */
            issuer: string;
            clientId: string;
        };
        Principal: {
            user: string;
            account: string;
            /** @enum {string} */
            role: "developer" | "viewer";
            /** @enum {string} */
            via: "identity" | "api-key";
            credentialId?: string;
        };
        /** @description The built component the controller pulls from the platform registry. */
        ComponentReference: {
            /** @description OCI reference the component was pushed as. */
            reference: string;
            /** @description sha256 digest of the pushed artifact. */
            digest: string;
        };
        /** @description One `@WasmCloudBinding` of the component, rendered by the CLI. */
        Binding: {
            name: string;
            capability: string;
            /** @description Backing service the binding attaches to. */
            serviceName?: string;
            config?: {
                [key: string]: string;
            };
        };
        /** @description Everything the CLI renders client-side. The controller validates it at the boundary and never receives a kubeconfig or a namespace. */
        DeployBundle: {
            /** @enum {string} */
            env: "prod" | "staging";
            /** @description Service the deployment belongs to. */
            service: string;
            component: components["schemas"]["ComponentReference"];
            /** @description The rendered WorkloadDeployment template, without namespace or host selector. */
            workload: {
                [key: string]: unknown;
            };
            bindings: components["schemas"]["Binding"][];
            /** @description Names of tenant secrets the workload references; values never travel. */
            secrets: string[];
        };
        /** @description Where a tenant pushes and pulls images: the tenant's own OCI registry. Log in with an identity-server access token or API key as the Basic password. */
        RegistryInfo: {
            /**
             * Format: uri
             * @description Origin of the tenant's OCI registry: scheme + host[:port], no path. Clients use its host[:port] for login and in image references; an http: origin means plain HTTP.
             */
            url: string;
            /** @description Namespace inside the tenant registry, when there is one. */
            repositoryPrefix?: string;
            /**
             * @description Basic auth whose password is an identity-server access token or dik_ API key.
             * @enum {string}
             */
            auth: "basic-identity";
            /** @description A fixed hint for the Basic username; the registry ignores it. */
            username: string;
        };
        DeployChange: {
            /** @enum {string} */
            kind: "create" | "update" | "unchanged" | "delete";
            resource: string;
            name: string;
            detail?: string;
        };
        /** @description What applying the bundle would change. */
        DeployPlan: {
            /** @enum {string} */
            env: "prod" | "staging";
            service: string;
            changes: components["schemas"]["DeployChange"][];
        };
        Deployment: {
            id: string;
            service: string;
            /** @enum {string} */
            env: "prod" | "staging";
            /** @enum {string} */
            status: "pending" | "rolling" | "ready" | "failed" | "rolled-back";
            component: components["schemas"]["ComponentReference"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            readyAt?: string;
        };
        DeploymentList: {
            items: components["schemas"]["Deployment"][];
        };
        DeploymentStats: {
            /** @enum {string} */
            env: "prod" | "staging";
            /** Format: int32 */
            services: number;
            /** Format: int32 */
            deployments: number;
            /** Format: int32 */
            ready: number;
            /** Format: int32 */
            failed: number;
            /** Format: date-time */
            lastDeployedAt?: string;
        };
        RollbackRequest: {
            /** @enum {string} */
            env: "prod" | "staging";
            service: string;
            /** @description Deployment id to roll back to; the previous one when absent. */
            to?: string;
        };
        /** @description Type-specific fields follow the type: `port` and `route` for http, `schedule` for cron, `command` for worker. */
        CreateServiceRequest: {
            /** @enum {string} */
            env: "prod" | "staging";
            /** @enum {string} */
            type: "http" | "cron" | "worker";
            name: string;
            /** Format: int32 */
            port?: number;
            /** @description Public route pattern for an http service. */
            route?: string;
            /** @description Cron expression for a cron service. */
            schedule?: string;
            /** @description Entry command of a worker service. */
            command?: string[];
        };
        Service: {
            name: string;
            /** @enum {string} */
            env: "prod" | "staging";
            /** @enum {string} */
            type: "http" | "cron" | "worker";
            route?: string;
            /** Format: int32 */
            port?: number;
            schedule?: string;
            command?: string[];
            /** Format: date-time */
            createdAt: string;
        };
        /** @description One line of a service log. Streamed as `text/event-stream`: each SSE `data:` field is one LogEvent as JSON; the `event:` field is `log`, or `end` when the stream closes. */
        LogEvent: {
            /** Format: date-time */
            timestamp: string;
            deployment: string;
            instance?: string;
            /** @enum {string} */
            level?: "debug" | "info" | "warn" | "error";
            message: string;
        };
        /** @description A secret lists its name only; a var also carries its value. */
        ConfigEntry: {
            name: string;
            value?: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ConfigList: {
            /** @enum {string} */
            env: "prod" | "staging";
            items: components["schemas"]["ConfigEntry"][];
        };
        /** @description A secret lists its name and update time only; its value never travels on read. */
        SecretEntry: {
            name: string;
            /** Format: date-time */
            updatedAt: string;
        };
        SecretList: {
            /** @enum {string} */
            env: "prod" | "staging";
            items: components["schemas"]["SecretEntry"][];
        };
        ConfigValue: {
            value: string;
        };
        ProxyRequest: {
            /** @enum {string} */
            env: "prod" | "staging";
            /**
             * Format: int32
             * @description Service port to tunnel to; the service default when absent.
             */
            port?: number;
        };
        /** @description A short-lived tunnel to one service. The CLI connects to `url` with the same bearer; the tunnel transport is WebSocket and is described outside this document. */
        ProxySession: {
            /** Format: uri */
            url: string;
            /** Format: int32 */
            port: number;
            /** Format: date-time */
            expiresAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    authInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Describe how to log in */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        account: string;
                        /** Format: uri */
                        issuer: string;
                        clientId: string;
                    };
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description Revoke the credential */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    whoami: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resolve the caller */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        user: string;
                        account: string;
                        /** @enum {string} */
                        role: "developer" | "viewer";
                        /** @enum {string} */
                        via: "identity" | "api-key";
                        credentialId?: string;
                    };
                };
            };
        };
    };
    deploy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    env: "prod" | "staging";
                    /** @description Service the deployment belongs to. */
                    service: string;
                    component: components["schemas"]["ComponentReference"];
                    /** @description The rendered WorkloadDeployment template, without namespace or host selector. */
                    workload: {
                        [key: string]: unknown;
                    };
                    bindings: components["schemas"]["Binding"][];
                    /** @description Names of tenant secrets the workload references; values never travel. */
                    secrets: string[];
                };
            };
        };
        responses: {
            /** @description Apply a deployment */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        service: string;
                        /** @enum {string} */
                        env: "prod" | "staging";
                        /** @enum {string} */
                        status: "pending" | "rolling" | "ready" | "failed" | "rolled-back";
                        component: components["schemas"]["ComponentReference"];
                        /** Format: date-time */
                        createdAt: string;
                        /** Format: date-time */
                        readyAt?: string;
                    };
                };
            };
        };
    };
    previewDeploy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    env: "prod" | "staging";
                    /** @description Service the deployment belongs to. */
                    service: string;
                    component: components["schemas"]["ComponentReference"];
                    /** @description The rendered WorkloadDeployment template, without namespace or host selector. */
                    workload: {
                        [key: string]: unknown;
                    };
                    bindings: components["schemas"]["Binding"][];
                    /** @description Names of tenant secrets the workload references; values never travel. */
                    secrets: string[];
                };
            };
        };
        responses: {
            /** @description Preview a deployment */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        env: "prod" | "staging";
                        service: string;
                        changes: components["schemas"]["DeployChange"][];
                    };
                };
            };
        };
    };
    registry: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get the tenant registry */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Format: uri
                         * @description Origin of the tenant's OCI registry: scheme + host[:port], no path. Clients use its host[:port] for login and in image references; an http: origin means plain HTTP.
                         */
                        url: string;
                        /** @description Namespace inside the tenant registry, when there is one. */
                        repositoryPrefix?: string;
                        /**
                         * @description Basic auth whose password is an identity-server access token or dik_ API key.
                         * @enum {string}
                         */
                        auth: "basic-identity";
                        /** @description A fixed hint for the Basic username; the registry ignores it. */
                        username: string;
                    };
                };
            };
        };
    };
    deployments: {
        parameters: {
            query: {
                env: "prod" | "staging";
                service?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List deployments */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Deployment"][];
                    };
                };
            };
        };
    };
    deploymentStats: {
        parameters: {
            query: {
                env: "prod" | "staging";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Summarize deployments */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        env: "prod" | "staging";
                        /** Format: int32 */
                        services: number;
                        /** Format: int32 */
                        deployments: number;
                        /** Format: int32 */
                        ready: number;
                        /** Format: int32 */
                        failed: number;
                        /** Format: date-time */
                        lastDeployedAt?: string;
                    };
                };
            };
        };
    };
    rollback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    env: "prod" | "staging";
                    service: string;
                    /** @description Deployment id to roll back to; the previous one when absent. */
                    to?: string;
                };
            };
        };
        responses: {
            /** @description Roll a service back */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        service: string;
                        /** @enum {string} */
                        env: "prod" | "staging";
                        /** @enum {string} */
                        status: "pending" | "rolling" | "ready" | "failed" | "rolled-back";
                        component: components["schemas"]["ComponentReference"];
                        /** Format: date-time */
                        createdAt: string;
                        /** Format: date-time */
                        readyAt?: string;
                    };
                };
            };
        };
    };
    secrets: {
        parameters: {
            query: {
                env: "prod" | "staging";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List secrets */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        env: "prod" | "staging";
                        items: components["schemas"]["SecretEntry"][];
                    };
                };
            };
        };
    };
    setSecret: {
        parameters: {
            query: {
                env: "prod" | "staging";
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    value: string;
                };
            };
        };
        responses: {
            /** @description Set a secret */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    unsetSecret: {
        parameters: {
            query: {
                env: "prod" | "staging";
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Unset a secret */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateSecret: {
        parameters: {
            query: {
                env: "prod" | "staging";
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    value: string;
                };
            };
        };
        responses: {
            /** @description Update a secret */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createService: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    env: "prod" | "staging";
                    /** @enum {string} */
                    type: "http" | "cron" | "worker";
                    name: string;
                    /** Format: int32 */
                    port?: number;
                    /** @description Public route pattern for an http service. */
                    route?: string;
                    /** @description Cron expression for a cron service. */
                    schedule?: string;
                    /** @description Entry command of a worker service. */
                    command?: string[];
                };
            };
        };
        responses: {
            /** @description Create a service */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        name: string;
                        /** @enum {string} */
                        env: "prod" | "staging";
                        /** @enum {string} */
                        type: "http" | "cron" | "worker";
                        route?: string;
                        /** Format: int32 */
                        port?: number;
                        schedule?: string;
                        command?: string[];
                        /** Format: date-time */
                        createdAt: string;
                    };
                };
            };
        };
    };
    logs: {
        parameters: {
            query: {
                env: "prod" | "staging";
                deployment?: string;
                follow?: boolean;
                since?: string;
                tail?: number;
            };
            header?: never;
            path: {
                service: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Read or follow service logs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: date-time */
                        timestamp: string;
                        deployment: string;
                        instance?: string;
                        /** @enum {string} */
                        level?: "debug" | "info" | "warn" | "error";
                        message: string;
                    };
                };
            };
        };
    };
    proxy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                service: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    env: "prod" | "staging";
                    /**
                     * Format: int32
                     * @description Service port to tunnel to; the service default when absent.
                     */
                    port?: number;
                };
            };
        };
        responses: {
            /** @description Open a tunnel to a service */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uri */
                        url: string;
                        /** Format: int32 */
                        port: number;
                        /** Format: date-time */
                        expiresAt: string;
                    };
                };
            };
        };
    };
    setVar: {
        parameters: {
            query: {
                env: "prod" | "staging";
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    value: string;
                };
            };
        };
        responses: {
            /** @description Set a var */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    unsetVar: {
        parameters: {
            query: {
                env: "prod" | "staging";
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Unset a var */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateVar: {
        parameters: {
            query: {
                env: "prod" | "staging";
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    value: string;
                };
            };
        };
        responses: {
            /** @description Update a var */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    vars: {
        parameters: {
            query: {
                env: "prod" | "staging";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List vars */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        env: "prod" | "staging";
                        items: components["schemas"]["ConfigEntry"][];
                    };
                };
            };
        };
    };
}
