[package]
name = "oci-registry-publisher"
version = "0.0.0"
workspace = "../../.."
edition.workspace = true
license.workspace = true
publish = false
description = "Build and publish the OCI registry Wasm component"
build = "build.rs"

[[bin]]
name = "oci-registry-publisher"
path = "main.rs"

[dependencies]
serde_json = "1.0"
sha2 = "0.10"
